#Liste des étudiants
ft_liste_etudiants:
    path: /personne/listeEtudiants
    defaults: { _controller: FTProjetStageBundle:Etudiant:liste }

#Équipes dont la personne en question est propriétaire
ft_personne_mesEquipes_proprietaire:
    path: /personne/mesEquipesProprietaire/{id}
    defaults: { _controller: FTProjetStageBundle:Etudiant:mesEquipesProprietaire }
    requirements:
        id: \d+

ft_etudiant_mesEquipes:
    path: /personne/mesEquipes/{id}
    defaults: { _controller: FTProjetStageBundle:Etudiant:mesEquipes }
    requirements:
        id: \d+