services:
#    upload.example:
#        class: FT\UploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    upload.annotation_reader:
        class: FT\UploadBundle\Annotation\UploadAnnotationReader
        arguments: ["@annotations.reader"]

    upload.handler:
        class: FT\UploadBundle\Handler\UploadHandler

    upload.subscriber:
        class: FT\UploadBundle\Listener\UploadSubscriber
        arguments: ["@upload.annotation_reader", "@upload.handler"]
        tags:
          - { name: doctrine.event_subscriber, connection: default }