ft_projet_stage:
    resource: "@FTProjetStageBundle/Resources/config/routing.yml"
    prefix:   /

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /


#login et logout
login:
    path: /login
    defaults:
        _controller: FTProjetStageBundle:Registration:login
login_check:
    path: /login_check
logout:
    path: /logout
personne_redirect:
    path: /personne/redirect
    defaults:
        _controller: FTProjetStageBundle:Registration:loginRedirect

#JSRouting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"