ft_projet_stage:
    resource: "@FTProjetStageBundle/Resources/config/routing.yml"
    prefix:   /

#login et logout
login:
    path: /login
    defaults:
        _controller: FTProjetStageBundle:Registration:login
login_check:
    path: /login_check
logout:
    path: /logout