security:
    provider: db_provider
    encoders:
        FT\ProjetStageBundle\Entity\Personne: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_FORMATEUR, ROLE_ETUDIANT]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: FTProjetStageBundle:Personne
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            provider: db_provider
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: personne_redirect
                always_use_default_target_path: true
                #csrf_token_generator: security.csrf.token_manager
            logout:
                path:   logout
                target: login
                #this customizes the redirect after the login
            remember_me:
                secret: '%secret%'
                lifetime: 604800  # 1week in seconds
                path:   /
                always_remember_me: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }

        - { path: /personne/mesProjetsProprietaire, roles: [ROLE_FORMATEUR] }
        - { path: /personne/creerProjet, roles: [ROLE_FORMATEUR] }

        - { path: /personne/creerEquipe, roles: [ROLE_ETUDIANT] }
        - { path: /personne/mesEquipes, roles: [ROLE_ETUDIANT] }

        - { path: ^/personne, roles: [ROLE_ETUDIANT, ROLE_FORMATEUR] }