#Page d'accueil
ft_projet_stage_homepage:
    path:     /
    defaults: { _controller: FTProjetStageBundle:Accueil:index }

#Tout ce qui concerne l'authentification, l'inscription, etc ...
ft_registration:
    resource: "@FTProjetStageBundle/Resources/config/Registration/routing_registration.yml"

#Profil utilisateur, dashboard
ft_personne:
    resource: "@FTProjetStageBundle/Resources/config/Personne/routing_personne.yml"

#Tout ce qui touche à l'étudiant
ft_etudiant:
    resource: "@FTProjetStageBundle/Resources/config/Etudiant/routing_etudiant.yml"

#Tout ce qui touche au formateur
ft_formateur:
    resource: "@FTProjetStageBundle/Resources/config/Formateur/routing_formateur.yml"

#Tout ce qui touche à l'équipe
ft_equipe:
    resource: "@FTProjetStageBundle/Resources/config/Equipe/routing_equipe.yml"

#Tout ce qui touche au projet
ft_projet:
    resource: "@FTProjetStageBundle/Resources/config/Projet/routing_projet.yml"

#Tout ce qui touche à l'admin
ft_admin:
    resource: "@FTProjetStageBundle/Resources/config/Admin/routing_admin.yml"

#Tout ce qui touche à la recherche
ft_search:
    resource: "@FTProjetStageBundle/Resources/config/Search/routing_search.yml"

#Tout ce qui touche au chat
ft_chat:
    resource: "@FTProjetStageBundle/Resources/config/Chat/routing_chat.yml"