ft_projet_stage_homepage:
    path:     /
    defaults: { _controller: FTProjetStageBundle:Accueil:index }

#Connexion utilisateur
ft_user_connexion:
    path:     /login
    defaults: {_controller: FTProjetStageBundle:Registration:login }
#Inscription utilisateur
ft_user_inscription:
    path:     /registration
    defaults: {_controller: FTProjetStageBundle:Registration:registration }
#Reset password utilisateur
ft_user_reset_password:
    path:     /resetPassword
    defaults: {_controller: FTProjetStageBundle:Registration:vueResetPassword }
