ft_projet_stage_homepage:
    path:     /
    defaults: { _controller: FTProjetStageBundle:Accueil:index }

#Connexion utilisateur
ft_personne_connexion:
    path:     /login
    defaults: {_controller: FTProjetStageBundle:Registration:login }
#Inscription utilisateur
ft_personne_inscription:
    path:     /registration
    defaults: {_controller: FTProjetStageBundle:Registration:registration }
#Reset password utilisateur
ft_personne_modif_password:
    path:     /resetPassword
    defaults: {_controller: FTProjetStageBundle:Personne:modifPassword }
ft_personne_profile:
    path: /personne/profile
    defaults: {_controller: FTProjetStageBundle:Personne:profile }
ft_liste_etudiants:
    path: /listeEtudiants
    defaults: {_controller: FTProjetStageBundle:Etudiant:liste }