ft_projet_stage_homepage:
    path:     /
    defaults: { _controller: FTProjetStageBundle:Accueil:index }

#Connexion utilisateur
ft_user_connexion:
    path:     /connexion
    defaults: {_controller: FTProjetStageBundle:Registration:vueConnexion }
#Inscription utilisateur
ft_user_inscription:
    path:     /inscription
    defaults: {_controller: FTProjetStageBundle:Registration:vueInscription }
#Reset password utilisateur
ft_user_reset_password:
    path:     /resetPassword
    defaults: {_controller: FTProjetStageBundle:Registration:vueResetPassword }
