<?php

namespace FT\ProjetStageBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPersonneLikeNom($nom)
    {
        return $this->createQueryBuilder('p')
            ->where('p.nom LIKE :nom')->setParameter('nom', '%' . $nom . '%')
            ->getQuery()->getResult();
    }

    public function getPersonneLikeMail($mail)
    {
        return $this->createQueryBuilder('p')
            ->where('p.email LIKE :email')->setParameter('email', '%' . $mail . '%')
            ->getQuery()->getResult();
    }

    public function getPersonneLikeNomOrMail($nomMail)
    {
        return $this->createQueryBuilder('p')
            ->where('p.nom LIKE :nomMail')->setParameter('nomMail', '%' . $nomMail . '%')
            ->orWhere('p.email LIKE :nomMail')->setParameter('nomMail', '%' . $nomMail . '%' )
            ->getQuery()->getResult();
    }

    public function getPersonneWithMailOrUsername($username, $mail)
    {
        return $this->createQueryBuilder('p')
            ->where('p.username = :username')->setParameter('username', $username)
            ->orWhere('p.email = :mail')->setParameter('mail', $mail)
            ->getQuery()->getResult();
    }
}
