<?php

namespace FT\ProjetStageBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjetLikeTitre($titre)
    {
        return $this->createQueryBuilder('p')
            ->where('p.titre LIKE :titre')->setParameter('titre', '%' . $titre . '%')
            ->getQuery()->getResult();
    }

    public function getProjetLikeSujet($sujet)
    {
        return $this->createQueryBuilder('p')
            ->where('p.sujet LIKE :sujet')->setParameter('sujet', '%' . $sujet . '%')
            ->getQuery()->getResult();
    }
}